site_name: Machine Learning
site_author: Dutra, G.
site_url: https://snowdutra.github.io/Machine-Learning/
repo_url: https://github.com/snowdutra/Machine-Learning/
repo_name: github/Machine-Learning

theme:
  name: material
  palette:
    # primary: grey
    # Light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: orange
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
  navigation:
    expand: false
  icon:
    # logo: assets/images/devops
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - markdown_grid_tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true  
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - tables
      
plugins:
  # - git-committers:
  #     repository: snowdutra/Machine-Learning
  #     branch: main
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-authors
  - search
  - badges
  - minify:
      minify_html: true
  - markdown-exec
  - render_swagger:
      allow_arbitrary_locations : true
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  - https://unpkg.com/mathjax/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js

nav:
  - Home: index.md
  - Documentation: ./documentation/main.md
  - √Årvore de Decis√£o:
    - 01.Introdu√ß√£o: ./arvore_decisao/01.introducao.md
    - 02.Importa√ß√£o de Bibliotecas: ./arvore_decisao/02.importacao_bibliotecas.md
    - 03.Carregamento do Dataset: ./arvore_decisao/03.carregamento_dataset.md
    - 04.An√°lise Explorat√≥ria: ./arvore_decisao/04.analise_exploratoria.md
    - 05.Visualiza√ß√£o das Notas: ./arvore_decisao/05.visualizacao_notas.md
    - 06.Correla√ß√£o entre Vari√°veis: ./arvore_decisao/06.correlacao_variaveis.md
    - 07.Compara√ß√£o por G√™nero e Grupo √âtnico: ./arvore_decisao/07.comparacao_grupos.md
    - 08.Pr√©-processamento: ./arvore_decisao/08.preprocessamento.md
    - 09.Divis√£o Treino/Teste: ./arvore_decisao/09.divisao_treino_teste.md
    - 10.Treinamento do Modelo: ./arvore_decisao/10.treinamento_modelo.md
    - 11.Otimiza√ß√£o do Modelo: ./arvore_decisao/11.otimizacao_modelo.md
    - 12.Avalia√ß√£o do Modelo: ./arvore_decisao/12.avaliacao_modelo.md
    - 13.√Årvore de Decis√£o Visual: ./arvore_decisao/13.arvore_visual.md
    - 14.Relat√≥rio Final: ./arvore_decisao/14.relatorio_final.md
  - KNN:
    - 01.Introdu√ß√£o: ./knn/01.introducao.md
    - 02.Importa√ß√£o de Bibliotecas: ./knn/02.importacao_bibliotecas.md
    - 03.Carregamento do Dataset: ./knn/03.carregamento_dataset.md
    - 04.An√°lise Explorat√≥ria: ./knn/04.analise_exploratoria.md
    - 05.Visualiza√ß√£o das Notas: ./knn/05.visualizacao_notas.md
    - 06.Correla√ß√£o entre Vari√°veis: ./knn/06.correlacao_variaveis.md
    - 07.Compara√ß√£o por G√™nero e Grupo √âtnico: ./knn/07.comparacao_grupos.md
    - 08.Pr√©-processamento: ./knn/08.preprocessamento.md
    - 09.Divis√£o Treino/Teste: ./knn/09.divisao_treino_teste.md
    - 10.Treinamento do Modelo: ./knn/10.treinamento_modelo.md
    - 11.Avalia√ß√£o do Modelo: ./knn/11.avaliacao_modelo.md
    - 12.Relat√≥rio Final: ./knn/12.relatorio_final.md
  - K-Means:
    - 01.Introdu√ß√£o: ./kmeans/01.introducao.md
    - 02.Importa√ß√£o de Bibliotecas: ./kmeans/02.importacao_bibliotecas.md
    - 03.Carregamento do Dataset: ./kmeans/03.carregamento_dataset.md
    - 04.An√°lise Explorat√≥ria: ./kmeans/04.analise_exploratoria.md
    - 05.Visualiza√ß√£o das Notas: ./kmeans/05.visualizacao_notas.md
    - 06.Correla√ß√£o entre Vari√°veis: ./kmeans/06.correlacao_variaveis.md
    - 07.Compara√ß√£o por G√™nero e Grupo √âtnico: ./kmeans/07.comparacao_grupos.md
    - 08.Pr√©-processamento: ./kmeans/08.preprocessamento.md
    - 09.Divis√£o Treino/Teste: ./kmeans/09.divisao_treino_teste.md
    - 10.Treinamento do Modelo: ./kmeans/10.treinamento_modelo.md
    - 11.Avalia√ß√£o do Modelo: ./kmeans/11.avaliacao_modelo.md
    - 12.Relat√≥rio Final: ./kmeans/12.relatorio_final.md
 
  - M√©tricas e Avalia√ß√£o:
    - 01.Introdu√ß√£o: ./metrica_avaliacao/01.introducao.md
    - 02.M√©tricas: ./metrica_avaliacao/02.metricas.md
    - 03.Preprocessamento: ./metrica_avaliacao/03.preprocessamento.md
    - 04.An√°lise Explorat√≥ria: ./metrica_avaliacao/04.analise_exploratoria.md
    - 05.Divis√£o Treino/Teste: ./metrica_avaliacao/05.divisao_treino_teste.md
    - 06.Treinamento do Modelo: ./metrica_avaliacao/06.treinamento_modelo.md
    - 07.Resultados: ./metrica_avaliacao/07.resultados.md
    - 08.Relat√≥rio Final: ./metrica_avaliacao/08.relatorio_final.md
    - [Baixar notebook Jupyter](https://github.com/snowdutra/Machine-Learning/raw/main/docs/metrica_avaliacao/metrica_avaliacao.ipynb)